import Head from 'next/head';
import { Asap_Condensed, Inter } from 'next/font/google';
import { ListManagement } from '@/layouts/List/ListManagement';
import { StepManagement } from '@/layouts/Step01/StepManagement';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* KDT */}
      {/* <ListManagement /> */}
      {/* 충남 */}
      <StepManagement />
    </>
  );
}
